M48
; DRILL file {KiCad 7.0.1} date Sat Apr 15 09:39:33 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-04-15T09:39:33+07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.950
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C1.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C1.300
%
G90
G05
T1
X103.425Y-107.86
X103.425Y-113.64
T2
X127.8Y-139.85
X135.8Y-139.85
T3
X136.96Y-83.796
T4
X136.96Y-76.303
T0
M30
